framework:
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    serializer:
        enabled: true
        enable_annotations: true

    #esi: true
    #fragments: true
    php_errors:
        log: true
